### ISSUE TITLE
Dial Values not scaling

### ISSUE THREAD

**Issue by gasthecat** [HanSolo/SteelSeries-Canvas#17] opened 2015-03-31 12:53 UTC
Hi Mark,
I've just updated from 0.11.13 of the SteelSeries library to 0.14.14. It looks like the values on the Radial Gauge don't scale up  ie make the gauge bigger the numbers look smaller.
![image](https://cloud.githubusercontent.com/assets/11737237/6919219/23c0660e-d7ad-11e4-8623-a40ab8ebbdeb.png)
Thanks GtC

**Comment by mcrossley** [comment] 2015-03-31 15:01
Good catch, a single missing space in a string in the Radial gauge. It looks like that mistake has been there forever.

**Comment by mcrossley** [comment] 2015-03-31 15:10
Fixed in v0.14.15.

**Closed by mcrossley** 2015-03-31 15:10 UTC

**Comment by gasthecat** [comment] 2015-04-07 19:41
Hi Mark,Thanks for the very quick update on the dial scaling issue.
I've come across (probably not a bug more a missing function) a feature of the Display Gauge (both Single and Multi)There is no .getValue Function. is that by design?
Question on the OdoMeter incorporated in the Radial gauge can the decimal (Red on White) be removed (true/false switch) and can it be scaled ?
Thanks for all your hard work it sure saves me a lot of development time.
RegardsColin.

**Comment by mcrossley** [comment] 2015-04-07 20:02
"I've come across (probably not a bug more a missing function) a feature of the Display Gauge (both Single and Multi)There is no .getValue Function. is that by design?"

More, it was never added.

"Question on the OdoMeter incorporated in the Radial gauge can the decimal (Red on White) be removed (true/false switch) and can it be scaled ?"

The odometer is a separate object with its own initialisation parameters, the two of interest to you are probably "digits" (default 6), and "decimals" (default 1)

So set
```javascript
	params = {
		//...,
		odometerParams : {
			digits: 6,
			decimals: 0
		}
	};
```
to suppress the decimal display with a total of six figures visible. See the odometer 'gauge' for all the parameters available.

Can it be scaled - no, it is a fixed size in relation to the gauge, apart from the number of digits. You can create a separate odometer in its own canvas though.

**Comment by gasthecat** [comment] 2015-04-07 21:40
Hi Mark,Again thanks for the super fast response, very sneaky putting configs inside a config!The main reason why I've gone for the Odo within the Radial so that the pointer will ride over the Odo.
One more Question but not the last, is there a way to reduce he frame size I'd like one that's about 10px wide.The Radial looks unfinished without the frame but the std one is just too chunky.
Again thanks for your work.

**Comment by mcrossley** [comment] 2015-04-09 10:56
No, the radial frame is a fixed size, I did look at making it a
configurable width some time ago, but there are a lot of hard coded values
would need to change - I just don't have the time at the moment.
